# This is a sample build configuration for Java (Maven).
# Check our guides at https://confluence.atlassian.com/x/zd-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: maven:3.6.1

pipelines:
  branches:
    develop:
        -   step: #Its working
                name: Create Artifact
                services:
                    - docker
                caches:
                    - maven
                script: # Modify the commands below to build your repository.
                    - mvn package -B -Pprod verify jib:dockerBuild # -B batch mode makes Maven less verbose

    master:
      - step:
          name: Build and push docker image to the Heroku
          services:
            - docker
          caches:
            - maven
          deployment: Production
          script:
            - mvn package -B -Pprod verify jib:dockerBuild
            - curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
            - heroku container:login
            - docker tag influsuccess registry.heroku.com/$HEROKU_APP_NAME/web
            - docker push registry.heroku.com/$HEROKU_APP_NAME/web
            - heroku container:release web -a $HEROKU_APP_NAME
